software/drive/c1541.cc

Fixes data loss when a disk image was swapped via the disk swap feature before all contents have been written back to the filesystem. 
Before mounting the new disk image, poll() is called repeatedly until the disk is no longer marked dirty. Also uses proper SubsysCommands to perform the mount.

Write all disk image contents before swapping disk images

---

software/6502/sidcrt/memalloc.asm
software/6502/sidcrt/player/advanced/advancedplayer.asm
software/6502/sidcrt/sidcrt.asm
software/6502/sidcrt/songlengths.asm

These changes fixes an issue that the song length of the sub tunes are the same as the first sub tune.
Also issues are fixed for calculating the location of the advanced player.

Songlength and advanced player fixes

---

software/6502/sidcrt/player/advanced/keyboard.asm
software/6502/sidcrt/sidcrt.asm

Now the Ultimate menu is shown when runstop key is released to prevent going back to player immediately.

Changed behavior of pressing runstop key.

---

software/io/c64/c64.cc
software/io/c64/c64_subsys.cc

This commit repairs Superkernal Compatibility and FC3 emulation.

Regression fixes

---

software/6502/sidcrt/detectionwrapper.asm
software/6502/sidcrt/sidfx.asm

fixed getting SID info for 8580 model

---

software/u64/sid_device_fpgasid.cc

LED configurationof FPGASID works for Marty and me.

Fpgasidled

---

software/u64/sid_device_fpgasid.cc

Disable settings not available for firmware 09 of FPGASID

---

fpga/cart_slot/vhdl_source/all_carts_v4.vhd
software/filetypes/filetype_crt.cc
software/io/c64/c64.h

Support for nordic Power

---

fpga/1541/vhdl_source/via6522.vhd

These changes are verified in:
- VIC20, viavarious, via_sr and other misc tests from VICE. IFR tests
in via_sr are failing, because it expects timing on CA2 (cassette motor
input), which is affected by an external RC component.
- 1541 connected to C64: viavarious tests all pass
- BBC Micro: SD-Card adapter with heavy use of the shift register. It's
using an undocumented feautre: Mode 0 actually accepts input and loads the
shift register.

Update VIA - timer, shift register, and CB transition detection fixes

---

software/filesystem/blockdev_flash.cc
software/filesystem/blockdev_ram.cc

This is a regression fix for "DISK ERROR" messages in file browser since sommit a637fe9e9cf170c98f0c2f7fa2e8a0eb6baaed0c

Regression fix

---

software/u64/sid_device_fpgasid.cc

Fixes https://github.com/GideonZ/1541ultimate/issues/216

FPGASID filter bias should be handled as signed int

---

software/network/socket_dma.cc

Hi,
I found this to be useful after streaming and the machine is not in arms reach. If only we could power it on remotely as well. :-)

Implement SOCKET_CMD_POWEROFF

---

software/io/c64/c64_crt.cc
software/io/c64/c64_crt.h

You may remember, we've exchanged emails about this patch.

Make easyflash to work again properly

---

software/io/c64/c64.cc

Fix GEORAM at power on (U2/U2+)

---

fpga/cart_slot/vhdl_source/all_carts_v5.vhd
software/io/c64/c64_crt.cc

Support Super Snapshot 5 128k

---

software/filesystem/filesystem_d64.cc

Renaming files in DNP images did not work in subdirectories

Fix renaming files in DNP iamge

---

software/io/acia/modem.cc
software/io/acia/modem.h

I implemented the E command that allows turning on and off of the local echo.

Added support for turning local echo on and off

---

html/index.html

- Simplify show/hide of app pages
- Make empty lines between functions consistent

Minor cleanup of web app index.html

---

software/chan_fat/ff14/source/ff.c

The free disk space calculation done when pressing F4 in the menu on a UII+L is slow in certain circumstances.
With this optimization a 128GB USB stick with 512 byte sectors and 4k cluster size (4MByte bitmap) sees an 82% time reduction, from 18545ms to 3100ms.
Using USB disks/sticks with small cluster size avoids wasting disk space when storing large amounts of small files (.d64, .prg). For exFAT formatted disks however, the "free disk space" calculation is quite slow when using a small cluster size. The first time F4 is pressed after power on, the user interface freezes with no visual feedback until the calculation completes. Further presses of F4 are fast since the result is cached.
Optimizations:
- Read 4k bytes instead of 512 byte sectors (uses an existing 4k buffer)
- Pre-calculate …

Optimize the exFAT free disk space calculator

---

software/filesystem/disk.cc
software/filesystem/disk.h

Also includes some minor DRY refactoring to the MBR code.
Big thanks to Tee for helping to test and debug this one with partitions created under Windows!

Add support for reading GPT disks

---

html/index.html
software/api/route_machine.cc

Simple way to "pause/unpause" the C64 by having it enter/leave the Ultimate menu.

Add menu button API and web page button

---

software/api/routes.cc
software/network/network_config.cc
software/network/network_config.h
software/network/socket_dma.cc

Makes it possible to disable Unique ID or change the ID to a custom value.

Make Unique ID configurable
