GideonZ/1541ultimate

software/application/ultimate/ultimate.cc
software/filetypes/filetype_reu.cc
software/io/c64/c64.cc
software/io/c64/c64.h
software/io/c64/reu_preloader.cc
software/io/c64/reu_preloader.h
target/software/mb_ultimate/Makefile
target/software/nios2_ultimate/Makefile

Adds three new configuration options to "C64 and cartridge settings":
REU Preload (Enable/Disable)
REU Preload Image (path)
REU PRELOAD Offset (128k - 16M)
If preload is enabled, the specified image will be loaded as soon as
the corresponding filesystem is available, starting at the specified
offset. If the image size exceeds the available REU memory space, the
image is only loaded up to the end of REU memory. No action is taken
if the specified offset is greater or equal to the available REU size.
In addition, this commit adds a "Set as Preload Image" option to the
REU file type.

Add options to preload a REU image on startup

---

software/io/c64/c64.cc

When adding the new REU preload options, a piece of code was overlooked that
adjusts the PHI timing values at runtime for either u2plus or the u64.
This caused the option for the ultimate audio to use 16ns and 32ns as values
rather than enable/disable, and the phi timing options to use the wrong
values as well.
This commits corrects this and similar bugs in the future by looking up
CFG_C64_TIMING by id instead of index.

Fix display glitch in C64 and cartridge settings menu

---

software/6502/sidcrt/Makefile
software/6502/sidcrt/player/advanced/keyboard.asm
software/6502/sidcrt/relocator.asm
software/6502/sidcrt/sidcrt.asm
software/6502/sidcrt/songlengths.asm

Some code cleanup and saved some more bytes in the relocator asm file.
The runstop key support is now made optional for the advanced player. This is needed when it is used by ACID64 where UCI is turned off by default. The runstop key is enabled by default for the sidcrt.

Code cleanup and runstop key support is now made optional

---

software/u64/u64_config.cc

C64_STEREO_ADDRSEL has to be unset during configuration. If it happens to be A8, configuration of the FPGASID in the 2nd socket does not work properly.

Fix C64_STEREO_ADDRSEL during detection and configuration

---

software/u64/sid_device_fpgasid.cc
software/u64/sid_device_fpgasid.h
software/u64/u64_config.cc
software/u64/u64_config.h

Hi Gideon,
this change allows detection of the adapter for 1 FPGASID from dukestah - so the user does not need to configure it.

Detect Dukestah Adapter + better support for it

---

software/io/c64/c64.cc

This fixes unavailable custom module types on Ultimate 64

Reenable Custom Final V1/V2 ROM and Custom CRT

---

software/filetypes/filetype_d64.cc
software/filetypes/filetype_d64.h
software/io/c64/c64.cc
software/io/c64/c64.h
software/io/c64/c64_subsys.cc

This patch enables the filebrowser to load an D41, D71, D81 and DNP file into the RAMDISK of Geos 1.3 to 2.0 and Geos Megapatch 3.3 R6 and most probably later. It also enables the filebrowser to save the content of the RAMDISK of the mentioned GEOS versions to an image file.
Note: Ramdisk type and image type must match. And in case of DNP the size must match, too.
Another Note: Geos 2.0 and below do not support DNP Ramdisks, so you cannnot load a DNP file to them.

Geos Ramdisk Support

---

fpga/cart_slot/vhdl_source/all_carts_v4.vhd

This change makes AR and NP emulation more like the original by removing extensions to the modules the original does not have.
If the extensions are needed in future, they should become another module type named 'nordic replay'.

Fix Action Replay & Nordic Power

---

fpga/cart_slot/vhdl_source/all_carts_v4.vhd
fpga/cart_slot/vhdl_source/slot_server_v4.vhd
fpga/cart_slot/vhdl_source/slot_slave.vhd
software/filetypes/filetype_crt.cc

This patch removes the restiction that 16k kernal switch RAM, which is wrong.
It also prepairs for 24k kernals.

Support for 16k ROM

---

software/io/c64/reu_preloader.cc

REUPreloader needs to listen for eNodeAdded and eNodeUpdated, just like it was recently changed in HomeDirectory.

Fix reu preload not working #179

---

software/filetypes/filetype_d64.cc
software/io/c64/c64_subsys.cc

Due to an incorrect default setting in GEOS V2, which was adopted from MP3 for compatibility reasons, D71 disk images cannot be read directly.
This patch makes it work.
Now I have sucessfully loaded source code from all supported image types, so they all work.

Fix D71 loading into MP3 ramdisk

---

software/io/acia/modem.cc
software/io/acia/modem.h

This code should provide numeric response codes via atv0
also, fixed a potential issue of showing RING from calling side.  RING should only be sent to listener

Add numeric response codes to modem

---

roms/c64rom/basic/code26.s
roms/c64rom/kernal/editor.3.s
roms/c64rom/kernal/init.s
roms/c64rom/kernal/patches.s

Also changed Shift-RUN/STOP behaviour to be disk-friendly, and does not reset device# on load/save.   Used kernal patch area so to not shift bytes.

Patch to set default device#8 on init

---

software/io/usb/keyboard_usb.cc

The for statement on line 165 was clearing all bits of the
modi variable causing the if statements testing for the
shift state, to become NOPs. Fix this by making modi const
to prevent this from happening again and checking the modifier
bits using a mask.
Fixes issue #168.
Signed-off-by: Peter De Schrijver <p2@psychaos.be>

Fix USB keyboard shift handling

---

software/io/usb/keyboard_usb.cc

Ctrl Home on a USB keyboard was mapped to Home and the mapping for Ctrl
Insert was missing.
Signed-off-by: Peter De Schrijver <p2@psychaos.be>

Fix Ctrl Home for USB keyboards

---

roms/c64rom/kernal/uci.s

Fix HyperSpeed Kernal closing of device 3 (screen).
FB user reported this basic code crashes at the close statement:
10 open 8,3
20 close 8
After fix, code snip works fine.  FB user seems happier now.

Fix closing device 3 using HyperSpeed kernal 

---

software/userinterface/browsable.h
software/userinterface/browsable_root.h
software/userinterface/tree_browser_state.cc
software/userinterface/userinterface.cc
software/userinterface/userinterface.h

Adds an UI option to "User Interface Settings" -> "Filename overflow squeeze"
that allows user to select the squeeze point (None/Beginning/Middle/End)
Kind of fixes "Long file name, can name be scrolled?":
https://github.com/GideonZ/1541ultimate/issues/212

Squeeze file and directory names if they are too long

---

software/network/ftpd.cc

The format string for the MLST command was using %s for size while the size field is an int.
Signed-off-by: Peter De Schrijver <p2@psychaos.be>

Correct FTP MLST command

---

software/io/acia/modem.cc

There are more changes that need to be made to be more hayes accurate, but this one solves a problem when the modem is told to supply numeric response codes  (via ATV0 command).  It does so fine, for all responses except CONNECT responses.

fixed issue where modem returns wrong value

---

software/io/c64/transform.cc

International keyboards don't have the key that's mapped to those, so this change maps the key one row below that was previously unmapped and another unmapped key between Shift and Z.

Provide alternate mappings for pound/up-arrow.

---

software/io/c64/c64.cc

This patch adds Ramdisk Support for Geos 128 in the same way already supported for Geos 64 and Geos Megapatch 3.

Geos 128 RAMDISK Support

---

software/drive/c1541.cc
software/drive/c1541.h
software/drive/c1581.cc
software/drive/c1581.h
software/filemanager/dos.cc
software/io/command_interface/control_target.cc

CMD_GET_DRVINFO returned the hardware ID of the device (that is the one the DIP switches of the 1541 II are configured) instead of the software ID.
This patch improved the UCI call that by default the software ID is returned, but the calling programm can specify that the hardware ID is wanted.

Fix drv info

---

software/filemanager/dos.cc
software/filemanager/dos.h
software/io/command_interface/control_target.cc
software/io/command_interface/control_target.h

This patch enabled UCI loading disk images into the GEOS Ramdisk.

Geos RAMDISK support in UCI

---

software/userinterface/home_directory.cc

The function "Enter Home Directory" does not work anymore . I set it to "enabled" and selected a directory with C= + CLR HOME, but it does not jump there after power on, it stays in the root directory.
commit a04784e65c94a9418a4d16797c34a72b6f63a1b3
Date:   Sat Aug 20 00:57:41 2022 +0200
[WIP] Trying to get DDR2 memory stable on Lattice ECP5, using dynamic phase shift and locking PLL for sys clock.
has disabled its Task, probably by accident not restored later.

This might fix HomeDir on startup

---

software/drive/disk_image.cc

To reproduce the problem to be solved:
(1) Load a D64 image (or probably other image) into the Floppy Drive A
(2) F5, Drive A, Save Binary, Enter Filename
(3) Observe that the size is not the expected size, in case d64 it should be 683 × 256 ≈ 171k, but the filemanager shows 172k and its size is exactly 686 × 256.
This patch fixes that.

Fix writing Dxx Images

---

software/drive/disk_image.cc
software/drive/disk_image.h

This patch improves gcr decoding without significcantly being slower. Without it, some g64 do not decode correctly.

Fix GCR decoding

---

software/filesystem/filesystem_d64.cc

According to the manual of the FD2000, the number of tracks has to be in byte 8 of the BAM, not in byte 7:

Fix BAM of DNP Images (format)

---

software/io/c64/c64.cc

In Forum 64, it was found that GeoRAM together with UCI cannot be enabled. But they can work together.
Note that since REU and GeoRAM are set up by the same setting with different values, we know in advance that both are not enabled.

GeoRAM is indeed compatible with UCI

---

README.txt

Went through this 100 times last few days, but figured out the issues.  These updates will continue to allow fresh installs of Quartus and help the developer get set up.

Some additional install / setup info 

---

software/io/iec/iec.cc
software/io/printer/iec_printer.cc
software/io/printer/iec_printer.h

Printer must register to IEC so IEC has to exist before Printer. And therefore, don't call Printer methods from IEC constructor. On previous firmware versions (up to 3.10j) IEC and Printer objects were statically declared at compilation time. Now they are dynamically created at system startup.

Fix IEC and Printer objects initialization sequence

---

software/filemanager/dos.cc

Since the length was ANDed with 0x00FFFFFF, you cannot save a whole 16 MB REU at once. This is fixed.

Fix: Cannot save whole 16 MB REU at once

---

software/io/printer/mps_png.cc

This prevents holding the CPU for too long causing the USB task to timeout while accessing the USB drive.

Release CPU periodically while virtual printer is generating a PNG file

---

software/network/ftpd.cc

When the FTP socket listener accept() returns a negative number (aborted connection, no new socket created or other error) the current code just continues to do setsockopt() on the negative number then launches a new  FTPDaemonThread() which will likely just fail.
This patch ignores the failed accept() and goes back to waiting for new connections in accept().
There is a  "return -3" commented out, probably because this would terminate the entire FTP server just because one connection attempt was aborted.

Add missing session skip on failed accept() for ftp server

---

tools/promgen.c

tools/promgen.c no longer compiles with gcc14 because implicit declaration of memcmp which is now an error. This pull request adds the required include statement to this file.

add missing include in promgen.c to make gcc14 happy

---

software/components/config.cc

The code incorrectly started truncating configuration strings one byte before they needed to be truncated, thus only allowing max-1 long strings to be set.
Reproduction:
1. Press F2 to get to the Configuration menu.
2. Enter WiFi settings
3. Go to SSID (which has a limit of 22 chars at the moment) and hit Enter
4. Type "abcdefghijklmnopqrstu" (21 chars)
5. Hit Enter to save
6. Notice SSID is as entered
7. Hit Enter to edit SSID again
8. Add the 22nd character "v" and hit Enter
9. Notice how the SSID suddenly was truncated to "abcdefghijklmnopqrst*" (still just 21 chars).
Applying this commit fixes the problem allowing "abcdefghijklmnopqrstuv" (22 chars) to be configured.

Fix bug preventing config strings to be exactly their max length

---

software/io/stream/host_stream.cc
software/io/stream/host_stream.h
software/io/stream/screen_vt100.cc
software/io/stream/screen_vt100.h
software/userinterface/userinterface.cc

Avoids weird colors and attributes being active when the user returns to their terminal after a Telnet session ends.

Make sure users terminal is restored when exiting a Telnet session

---

software/portable/riscv/riscv_main.c
software/wifi/raw_c3/main/rpc_calls.h

NOTE: This PR is not toward "master" - it is toward "u64ii". I understand that branch is undergoing heavy development to get stuff ready for U64II, so please feel free to decline this PR if it is premature to do PRs there.
Either way, I managed to build and run the Ultimate app after applying the below fixes. I just did bare minimum and didn't add the event_pkt_connected struct which I noticed was added to the u64ctrl/main/rpc_calls.h file (I guess it is not needed for U2+ yet).

Make u64ii branch build for U2+L again

---

software/application/programmer/u64_programmer.cc
software/application/u64ii_tester/u64ii_programmer.cc
software/application/ultimate/ultimate.cc
software/application/update_u2p/update_u64.cc
software/application/update_u2p/update_u64ii.cc
software/filetypes/filetype_u2p.cc
software/filetypes/filetype_u2u.cc
software/network/socket_dma.cc
software/network/socket_gui.cc
software/system/product.cc
software/system/product.h
software/u64/u64_config.cc
software/u64/u64_config.h
target/u2/microblaze/mb_ultimate/Makefile
target/u2/riscv/ultimate/Makefile
target/u2plus/nios/recovery/Makefile
target/u2plus/nios/ultimate/Makefile
target/u2plus_L/riscv/ultimate/Makefile
target/u64/nios2/loader/Makefile
target/u64/nios2/ultimate/Makefile
target/u64/nios2/updater/Makefile
target/u64/riscv/ultimate/Makefile
target/u64ii/riscv/ultimate/Makefile

The code to identify which hardware (i.e which product) is being used is duplicated in several places.
This merge request moves all of that half-messy code into a single "product"  unit, removing code duplication and keeping the calling code cleaner. A couple of future merge requests rely on this refactoring.
Note: This MR is toward the u64ii branch since the changes also cover the new U64E2 support.

Gather product related functions in one place

---

software/system/product.cc

Make sure isEliteBoard() returns true for U64E2

---

software/io/printer/iec_printer.cc
software/io/printer/iec_printer.h

Calls the IEC interface configuration method when the printing device ID is changed. Otherwise, the printer's IEC interface continues to listen with the printer ID set at power-on. This will solve issue #464.

Reconfigure IEC interface when printer device ID is changed

---

software/network/ftpd.cc

The structure was accidentally initialized with bytes of 0x30 instead of 0x00.

Fix bug in ftp server sockaddr_in initialization

---

software/system/small_printf.cc

The default width for %x was zero causing an empty string to be inserted when no explicit width was supplied. Changed the default width to 8 (covers all data in the supplied 32 bit "int" argument). Also added protection against too large widths being specified.

Fix printf() replacing %x with an empty string

---

software/api/routes.cc
software/network/socket_dma.cc
software/system/product.cc
software/system/product.h

This is an ID which uniquely identifies the current Ultimate device. This allows Assembly64 (and other software) to recognize individual Ultimate units over time even if they change firmware version, hostname, ip or switch from LAN to WiFi (MAC address changes).
The latest beta of Assembly64 makes good use of this id to manage it's list of devices.

Add unique_id to UDP discovery packet and /v1/info API endpoint

---

software/userinterface/ui_elements.cc

**NOTE:** This PR covers the half of what still remains after #440 was closed.
When using keyboard shortcuts in popups an incorrect value is often returned from poll(), causing the wrong action to be taken.
The problem is that an "active button index" is returned rather than the expected "absolute button index".
Refactored code to return the correct value in all situations.
Bug reproduction:
1. Navigate to a random file you want to delete
2. Hit Enter
3. Select "Delete"
4. When you get the "Are you sure?" question popup, press the "Y" key on the keyboard - and you will see the file NOT being deleted
5. Try again, but press the "N" key, and the file WILL (incorrectly) be deleted

Fix incorrect keyboard shortcut actions in popups

---

software/io/wifi/wifi.cc
software/network/sock_echo.c

First fix is to ESP32 debug logging.
Second fix is to sock_echo.c which is not used at the moment.

Tiny fix for missing network to host byte order conversions

---

python/syslogd.py
software/application/ultimate/ultimate.cc
software/io/network/network_interface.cc
software/network/network_config.cc
software/network/network_config.h
software/network/syslog.cc
software/network/syslog.h
target/u2/microblaze/mb_ultimate/Makefile
target/u2/riscv/ultimate/Makefile
target/u2plus/nios/ultimate/Makefile
target/u2plus_L/riscv/ultimate/Makefile
target/u64/nios2/ultimate/Makefile
target/u64/riscv/ultimate/Makefile
target/u64ii/riscv/ultimate/Makefile

This feature is useful for developers to receive console logs over the network instead of having to connect to the physical serial debug port on the Ultimate board.
Logs are buffered fairly early in the boot, and when the network is available the logs will be sent to the configured syslog server. The server is specified as `ip:port` where the port is optional and defaults to the syslog port (514). If no syslog server is defined (default) then no logging will be done.
Changes to the syslog serve ip or port always require a restart of the Ultimate product.
A tiny but fully usable syslog server is included as `python/syslogd.py`.

Add support for logging to a remote syslog server

---

software/api/route_configs.cc

String settings with dynamically created lists of possible presets (CFG_TYPE_STRFUNC) were exposed in the API just as normal strings without the presets. This change adds a field "presets" containing the same values shown in the Ultimate Menu. This is similar to the "values" field for CFG_TYPE_VALUE.
The reason to use "presets" and not "values" is to make clear to the caller that an arbitrary string is also allowed (which it isn't for CFG_TYPE_VALUE with a "values" list).

Improve API for CFG_TYPE_STRFUNC config settings

---

software/userinterface/user_file_interaction.cc

Disabled the View, Rename and Delete actions for "Volumes". They either did nothing or gave weird behaviours for disk images. The Rename action does make sense and could be re-enabled once properly implemented.
Fixes #327.

Hide unsupported Volume file interactions

---

.github/workflows/build.yml

Some of the current workflow step names could be interpreted as the step will not include the FPGA cores. This change clarifies that the step will include cached FPGA cores.
Updated the ESP32 build step to make it clear that if the step is skipped it is due to the results already being in the cache.

Improve GitHub workflow step names

---

software/api/route_configs.cc
software/io/c64/c64.cc
software/network/network_config.cc
software/u64/u64_config.cc
software/userinterface/config_menu.h
software/userinterface/context_menu.cc

This PR avoids handling "empty" configuration settings presented for CFG_TYPE_STRFUNC as magically escaped strings. Instead a natural empty string is passed around and the screen renderer puts "- None -" in its place. This simplifies code as well.
The only visible change in the UI is that the U64 "Palette Definition" setting will now have "- None -" in the drop-down rather than "- Default -".

Clean up action string drop-downs for CFG_TYPE_STRFUNC

---

target/fpga/u2plus_ecp5/Makefile

We want the U2+L FPGA build to always terminate with a useful error if any of the primary nets in the bit stream are assigned to `i_riscv/*` signals. 
Note: This PR requires building the FPGA under Linux / git-bash. If this is not desirable please just decline this PR.

Update the U2+L FPGA build to stop when certain build problems are detected

---

software/userinterface/assembly_search.cc

Changed the word form to from in "downloaded form the internet."

Fix typo in Assembly64 help screen
